### PR TITLE
removed `Optional` on the specified datakey fields

### LINKED ISSUE #309: Add NotRequired things to the DataKey schema
As per https://github.com/bluesky/ophyd-async/pull/137#discussion_r1624442103

Also removing the `Optional` from "units" and "precision"

https://github.com/bluesky/event-model/blob/fc6e30eae896073eda4013f7c4af3362fead61c1/event_model/documents/event_descriptor.py#L59

### PR DESCRIPTION
**Pull request by evalott100**
Fixes half of #309

### CODE REVIEW

**Review by coretl — APPROVED** [review]
https://github.com/bluesky/event-model/issues/309 isn't a very well written ticket... This PR does half of it.

Please could you make another PR that adds `limits` and `choices` as per the link in the ticket and make them `NotRequired` fields.

**Review by DiamondJoseph — COMMENTED** [review]
Aren't units and precision optional though?
For a str enum precision doesn't make sense- are we just going to say 0 or -1? Empty units for dimensionless things yes

**Comment by coretl** [comment]
> Aren't units and precision optional though? For a str enum precision doesn't make sense- are we just going to say 0 or -1? Empty units for dimensionless things yes

We remove the ability to make them `null`. This means they don't need to be in the descriptor (e.g. `precision` for an enum), but if they **are** present they must be of the right type.

**Review by DiamondJoseph — APPROVED** [review]
That makes sense: precision is still NotRequired but if present is str not str | None

**Comment by evalott100** [comment]
> Please could you make another PR that adds `limits` and `choices` as per the link in the ticket and make them `NotRequired` fields.

May as well do it here

**Comment by evalott100** [comment]
@coretl I think I should maybe make each field `Optional` in `LimitsRange` (as opposed to `NotRequired`). EPICS does allow for low/high limits without high/low being set.

**Pull request merged**
