### PR TITLE
Dtype numpy

### PR DESCRIPTION
**Pull request by evalott100**
Replacing https://github.com/bluesky/event-model/pull/315

### CODE REVIEW

**Comment by evalott100** [comment]
@coretl @danielballan 

Despite the fact pydantic will fail correctly for the list field here:

https://github.com/bluesky/event-model/blob/94c7801d1d42a4ccff9da82d24721ec35d922dd3/event_model/tests/test_auth.py#L78-L88

The schema will not, it's because for some reason pydantic is outputting `prefixItems` instead of just `items` here:

https://github.com/bluesky/event-model/blob/94c7801d1d42a4ccff9da82d24721ec35d922dd3/event_model/schemas/event_descriptor.json#L76

**Comment by evalott100** [comment]
Inserting `"items": false` makes everything work, I'm not too sure why pydantic isn't doing this already.

``` json
                {
                            "items": {
                                "maxItems": 2,
                                "minItems": 2,
                                "prefixItems": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "description": "A numpy dtype e.g `<U9`, `<f16`",
                                        "pattern": "[|<>][tbiufcmMOSUV][0-9]+",
                                        "type": "string"
                                    }
                                ],
                                "items": false,
                                "type": "array"
                            },
                            "type": "array"
```

**Comment by evalott100** [comment]
For now we'll get around this by adding

```
_ConstrainedDtypeNpStructure = Annotated[
    Tuple[str, _ConstrainedDtype], Field(json_schema_extra={"items": False})
]
```

But I'll make an issue on pydantic.

**Comment by evalott100** [comment]
Okay I figured it out, we simply can't pass a tuple into the jsonschema... While it will do positional args differently, it requires the `array` to be a list... But then paradoxically to generate the correct schema which does have different constraints on `prefixItems` pydantic will need the type hint to be `Tuple`.

**Comment by evalott100** [comment]
@tacaswell implemented this to allow for tuples, but it isn't working in this case

https://github.com/python-jsonschema/jsonschema/issues/148#issuecomment-2058122215

**Review by coretl — APPROVED** [review]

**Comment by coretl** [comment]
fixes #308

**Pull request merged**
